name: tutorial_stage
description: A Flutter package for creating highly customized in-app tutorials.
version: 0.0.1
repository: https://www.github.com/iandis/tutorial_stage
issue_tracker: https://www.github.com/iandis/tutorial_stage/issues

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
